# Generated by Django 6.0.4 on 2026-04-27 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBJob',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Submitted', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeGroup',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='submitted', max_length=50)),
                ('actual_url', models.URLField(blank=True, null=True)),
                ('ai_generated_url', models.URLField(blank=True, null=True)),
                ('knowledge_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgegroup')),
            ],
        ),
    ]
